### ISSUE TITLE
Why is_array(object) return true?

### ISSUE THREAD

**Issue by liverbool** [locutusjs/locutus#110]
``` javascript
is_array({0: 'Kevin', 1: 'van', 2: 'Zonneveld'});
// return true

is_array([]);
//return true

is_array({});
//return true
```

It's should be: (?)

``` javascript
is_array([]);
//return true

is_array({});
//return false
```

I don't know that is a bug or a feature?

**Comment by geoidesic** [comment]
I don't understand how to change this ini setting? Confusing because `ini_set` is a PHP thing, so how is it relevant to JavaScript?

**Comment by aristath** [comment]
> Confusing because ini_set is a PHP thing, so how is it relevant to JavaScript?

This whole repository is about PHP things in JS... `ini_set()` is a port of PHP's `ini_set` function, converted to the context of this library.
