### ISSUE TITLE
Array issues

### ISSUE THREAD

**Issue by kukawski** [locutusjs/locutus#148]
I created this ticket as a continuation of issue #27 to discuss a strategy for handling arrays.

Some of our functions work properly with pure arrays, but fail on objects, because in some browsers key order is not preserved. I know that Brett has done some work on "custom" arrays (array wrapper function). And I think it could be the proper way if not some browser limitations. I have a strong believe that ES6 Proxies could really help here.

But all in all, we should discuss our strategy, so we have **one** strategy and everyone of us understands what we want to achieve and how to mark functions that fail for some conditions.

**Comment by kvz** [comment]
I'm currently leaning towards:

 - pretending a js object is a php array
 - putting up disclaimers that order cannot be guaranteed on all platforms
 - accepting defeat in this

For cases like `is_array`, I'd say JavaScript datatypes are first class citizens, meaning it shall return false on `{}` and true on `[]`, which the exception for when `iniVal` evaluates to `on` in:

```js
var iniVal = (typeof require !== 'undefined' ? require('../info/ini_get')('locutus.objectsAsArrays') : undefined) || 'on'
```

I'd like to avoid shipping our own datatypes.
