### ISSUE TITLE
[bower] semver git tags

### ISSUE THREAD

**Issue by ogonkov** [locutusjs/locutus#158]
Please, can you add semver tags for PHPJS releases?

Without it it's hard to manage PHPJS package via bower.

bower.io/#registering-packages

> Your package should use semver Git tags.
> Your package must be available at a Git endpoint (e.g., GitHub); remember to push your Git tags!

**Comment by mstred** [comment]
Hey guys, would it be at least feasible to apply the same versioning from [npm](https://www.npmjs.com/package/phpjs) releases here to the source repository?
