### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [locutusjs/locutus#307]
Hello @kvz ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the main file need to be grab on [npm](https://www.npmjs.com/package/locutus).
I think the main file is `locutus.js` under `website/themes/icarus/source/js/` on [github](https://github.com/kvz/locutus), right?
But I am not sure which file is needed to be grab on npm.
Please help me confirm that.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8494

**Comment by kvz** [comment]
Hi there, thanks for your consideration! We advice against using big locutus bundles. The file you found is just to run the website. If pressed, I'd say the individual functions might be useful, but I don't think locutus is a great fit for cdnjs use, it should be thought of more as a resource / inspiration than a production-ready library.
