### ISSUE TITLE
strotime not working with oracle date format

### ISSUE THREAD

**Issue by zendre4** [locutusjs/locutus#340]
Hello,

I have remark than the strotime function not working with the format "d-M-y".
This format is standard in Oracle database ?

Somebody can fix this ?

**Comment by kukawski** [comment]
@zendre4 I will fix it. Can you please post some example date strings so I'm 100% sure what does 'd', 'M' and 'y' mean? Thanks.

**Comment by zendre4** [comment]
Example with current date : 10-JUL-17

**Comment by kvz** [comment]
Fixed this in the associated commit 👌
