### ISSUE TITLE
array_multisort throws "Unable to delete property."

### ISSUE THREAD

**Issue by oleg-andreyev** [locutusjs/locutus#344]
Browser: PhantomJS
Code: 

```
'use strict`
array_multisort(["productIds[]", "_"], 'SORT_ASC', ["productIds[]=977385529", "_=1502965788347"])
```

Error: `array_multisort.js:171 Unable to delete property.`
`delete sortKeys[i]`

Ref.: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
>Third, strict mode makes attempts to delete undeletable properties throw (where before the attempt would simply have no effect):

```
'use strict';
delete Object.prototype; // throws a TypeError
```

**Comment by oleg-andreyev** [comment]
after creating `sortArrs[0]`, we're creating `sortArrs[2]` instead of `sortArrs[1]`, and because sequences is broken (not 0,1,2...) `sortArrs.length` will be 3, instead of 2

**Comment by oleg-andreyev** [comment]
We've found another issue but under Edge:

```
Calling delete on '0' is not allowed in strict mode
```

Near this line:

```
if (arguments[i].hasOwnProperty(k)) {
                                delete arguments[i][k];
                            }
```

**Comment by kvz** [comment]
Attempting something here: https://github.com/locutusjs/locutus/pull/472

No promises :)
