### ISSUE TITLE
New website address is incorrect

### ISSUE THREAD

**Issue by kurdtpage** [locutusjs/locutus#398]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description
Hey I noticed at https://www.npmjs.com/package/phpjs it has the incorrect address of "http://locutus.nl", it should be "https://locutus.io/"

**Comment by kvz** [comment]
Thank you for reporting!

I'm very late to the party, but fixed this just now 🙀 

<img width="833" alt="image" src="https://github.com/locutusjs/locutus/assets/26752/8d11936a-ae80-4a8b-b527-ede1376c7cb6">
