### ISSUE TITLE
number_format

### ISSUE THREAD

**Issue by rafaelg21** [locutusjs/locutus#410]
- [ ] Have you checked the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?

### Description
Hola, tengo un problema con esta función, la copie y pegue en mi proyecto sin descargar toda la librería pero su retorno no es correcto. ejemplo

number_format(1029,2,',','.');

//resultado 1.0.2.9,00

**Comment by kukawski** [comment]
I can't reproduce your issue. For your example call I get `1.029,00`. In what browser/environment did you run the code?
