### ISSUE TITLE
strtotime returns false on 2.0.11

### ISSUE THREAD

**Issue by rebelvg** [locutusjs/locutus#413]
### Description
Previously on versions prior to 2.0.11 like 2.0.10 or 2.0.9 it was possible to parse strings like `Mon Apr 27 18:49:44 2020`. On latest 2.0.11 it just returns false.

**Comment by kukawski** [comment]
I'll take a look.

**Comment by kukawski** [comment]
The parser that was introduced in 2.0.10 release falls with parsing "Apr 27 18" into datetextual category https://github.com/php/php-src/blob/73734eee6ca30953b9725f683738a141b6b28ebf/ext/date/lib/parse_date.re#L1454 so the remaining :49:44 is not recognized as time. I will try to adjust the rule order to get closer to PHP rules.

**Comment by kukawski** [comment]
PHP in turn recognizes it as dateshortwithtimelong, which is not yet supported. I will try to provide support within next days.

**Comment by rebelvg** [comment]
Thanks!

**Comment by kukawski** [comment]
Pull request implementing the missing date formats has just been merged to master.

**Comment by Falseclock** [comment]
`strtotime(new Date().toISOString())` also returns false

**Comment by kukawski** [comment]
@Falseclock this is probably due to yet missing timezone support. I will add some basic support (for `Z` and `[+-]HH:MM`) shortly.

**Comment by kukawski** [comment]
The following PR adds initial timezone support https://github.com/locutusjs/locutus/pull/432
Support for full timezone names will be added in separate PR.

**Comment by geoidesic** [comment]
For me `strtotime` is `undefined` after import. (locates: "^2.0.14").

**Comment by kukawski** [comment]
I'm closing the issue. If you think the issue is not properly solved, please feel free to re-open.
