### ISSUE TITLE
Unit tests in separate files?

### ISSUE THREAD

**Issue by kukawski** [locutusjs/locutus#415]
When porting functions like sprintf, serialize, unserialize or strtotime, I found it quite limiting to add unit tests in the comments. The functions are so complex that they require really many test cases to prevent regressions and adding them as comments inside the function body is IMHO not a good idea, because of the bloat and loss of readability.

How about moving tests out of the comments, just keep them in separate file, e.g. in same folder named {function}.test.js? We could still keep the comments to show examples how to call the functions properly. The comments could still be parsed and executed to make sure that examples still work.

**Comment by kvz** [comment]
I'm fine to have these files in addition, for sure :ok_hand: Shall we use Jest then?

**Comment by kvz** [comment]
Addressed here https://github.com/locutusjs/locutus/pull/468
