### ISSUE TITLE
fmod(): toFixed() digits argument must be between 0 and 100

### ISSUE THREAD

**Issue by dekairi** [locutusjs/locutus#417]
`fmod(10, 1)` causes the error:
Uncaught RangeError: toFixed() digits argument must be between 0 and 100
Possible solution:
```
else {
     return parseFloat(tmp2.toFixed(Math.abs(p))); // instead of (toFixed(-p))
}

```

**Comment by kvz** [comment]
Sorry for the late response, but this is fixed now in the referenced commit 🙌
