### ISSUE TITLE
Transitioning to an org

### ISSUE THREAD

**Issue by kvz** [locutusjs/locutus#421]
Hi @brettz9 @argosback @Theriault @kukawski @louisstow et al,

Locutus (php.js originally) has been advertised as a community driven project for a long time, and it's also working quite well this way. To embrace this model further and democratize the project, I've moved it out of my `kvz` handle into an org, and made all of you contributors, and @kukawski an owner, as he put in the most (and outstanding) work recently. 

Hope you're all doing well, nothing much needs to change, but if you want something to change, you now have stewardship to do so.

All the best, Kev

**Comment by brettz9** [comment]
Great--Good to know in case I may return to the code base. And good to hear from you...Hope you and all are well!

**Comment by kukawski** [comment]
Interesting things happening :) Thank you @kvz for inviting me to the locutusjs org. Nice to work with you on the project.
