### ISSUE TITLE
PHP `unserialize` breaking since last minor version

### ISSUE THREAD

**Issue by tcandens** [locutusjs/locutus#423]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/locutusjs/locutus/blob/master/CONTRIBUTING.md) document?

### Description
Looks like recent changes to `locutus/php/var/unserialize` have caused it to break in the presence of null values.
It is common for null to be serialized as a capital `N` and recent changes have removed the normalizing `toLowerCase` when checking the serialized members; `n !== N`

See this code for illustration of bug:
https://runkit.com/embed/p7h2lhfcf8gf

**Comment by kukawski** [comment]
Thank you for spotting and fixing this issue.
