### ISSUE TITLE
"contributing guidelines coding standards" url broken

### ISSUE THREAD

**Issue by divinity76** [locutusjs/locutus#429]
- [ ] Have you checked the guidelines in our [Contributing](https://github.com/locutusjs/locutus/blob/master/CONTRIBUTING.md) document?

### Description
when checking the contributing guidelines at https://github.com/locutusjs/locutus/blob/master/CONTRIBUTING.md , if you click on the "updated coding standards." link, you're greeted with this 404 error:
![image](https://user-images.githubusercontent.com/1874996/94006145-b36b4300-fd9f-11ea-91b3-a8a59cd8116f.png)

**Comment by kvz** [comment]
Thanks for reporting, this was fixed in the meantime https://github.com/locutusjs/locutus/blob/main/CONTRIBUTING.md
