### ISSUE TITLE
[c/stdio/sprintf] %% consumes an extra arg

### ISSUE THREAD

**Issue by paramsiddharth** [locutusjs/locutus#441]
- [x] Have you checked the guidelines in our [Contributing](https://github.com/locutusjs/locutus/blob/master/CONTRIBUTING.md) document?

# Description
## \[`c/stdio/sprintf`\] %% consumes an extra arg
When trying to use `%%` in `sprintf` to represent a `%` sign, it consumes an extra value from `...args`.

The following examples will explain it better:
- ``` js
  const str = sprintf('%d%%%d.', 1, 2);
  console.log(str);
  ```
  Output: `1%0.`
- ``` js
  const str = sprintf('%s is a %d%% %s %s.', 'Param', 90, 'good', 'boy');
  console.log(str);
  ```
  Output: `Param is a 90% boy undefined.`

If approved, I would like to work on this issue.

**Comment by kukawski** [comment]
@paramsiddharth thank you for reporting the bug. You are free to work on it. I'll then review the fix.

**Comment by kukawski** [comment]
@paramsiddharth do you plan to submit a fix soon? Otherwise I'm ready to prepare one.

**Comment by paramsiddharth** [comment]
> @paramsiddharth do you plan to submit a fix soon? Otherwise I'm ready to prepare one.

Yes! Pardon the delay! I'll let you know if I'm stuck. I'll make a PR soon!

**Comment by paramsiddharth** [comment]
@kukawski I just made PR #442 . Please review.

**Comment by kukawski** [comment]
Alright, the patch is now merged. Thanks for spotting the problem and fixing it.
