### ISSUE TITLE
Percentage for "similar_text"

### ISSUE THREAD

**Issue by emresaracoglu** [locutusjs/locutus#448]
Hello,

How can I get the result as a percentage?

https://github.com/locutusjs/locutus/blob/master/src/php/strings/similar_text.js

Thank you

**Comment by kukawski** [comment]
It's not possible in JavaScript to implement the function exactly like PHP does, so in order to get the percentage, call the function with `true` as last param.

```js
const resultPercent = similar_text("abc", "abc", true); // 100
```

**Comment by emresaracoglu** [comment]
@kukawski Thank you.
