### ISSUE TITLE
strip_tags has some differences with php's version

### ISSUE THREAD

**Issue by losnappas** [locutusjs/locutus#455]
```php
echo strip_tags("1<<<    a");
// => "1"
```
```js
console.log(strip_tags("1<<<    a"))
// => "1<<<    a"
```

https://github.com/locutusjs/locutus/blob/728ea4772a45dca8ff05bb2a50c75383f14127e4/src/php/strings/strip_tags.js#L51

that line esp has some problems: `strip_tags("1<<") // => "1<"`

It looks like php version counts `<` characters and then deletes everything until it finds a matching closing one.

**Comment by kvz** [comment]
Thanks for reporting. The core maintainers are low on time, would you like to PR a fix?
