### ISSUE TITLE
php similar_text performance

### ISSUE THREAD

**Issue by LordVersA** [locutusjs/locutus#459]
hi is there anyway to make this function's performance better? 
[src/php/strings/similar_text.js
](https://github.com/locutusjs/locutus/blob/aa2751437a92cc1b33204b5e1252e8ef899206ad/src/php/strings/similar_text.js)

**Comment by kukawski** [comment]
I can check if I can squeeze some more microseconds out of the code, but it's going to be difficult because even the PHPs function has `O(N**3)` complexity.

**Comment by LordVersA** [comment]
thanks for your answer,
is there any javascript function that work like this? and can get percentage of similarity? a more efficient way @kukawski

**Comment by kukawski** [comment]
Not exactly what you're looking for, but in this repository you will find function for calculating Levenshtein distance (src/php/strings/levenshtein.js).
Otherwise you can try out Jaro-Winkler similarity (https://www.geeksforgeeks.org/jaro-and-jaro-winkler-similarity/) which is `O(n*m)`.

**Comment by LordVersA** [comment]
> Not exactly what you're looking for, but in this repository you will find function for calculating Levenshtein distance (src/php/strings/levenshtein.js). Otherwise you can try out Jaro-Winkler similarity (https://www.geeksforgeeks.org/jaro-and-jaro-winkler-similarity/) which is `O(n*m)`.

thanks for your time <3
