### ISSUE TITLE
v2.0.17 requires yarn 4.x?

### ISSUE THREAD

**Issue by jweisb02** [locutusjs/locutus#467]
Projects that use classic yarn v1.22.22 don't seem to work with this new version starting at 2.0.17, as it claims it requires yarn 4.x.  to be installed. 
`locutus@2.0.29: The engine "yarn" is incompatible with this module. Expected version "4.0.1". Got "1.22.22"`

I believe yarn classic v1.22.22 is still heavily used

**Comment by evereq** [comment]
Agree with @jweisb02, it just broke our builds where we seem to have deps on `twing` package which itself uses `locutus` (https://gitlab.com/nightlycommit/twing/-/blob/main/package.json?ref_type=heads#L51)

I think @kvz such a minor version increase (2.0.*) introduces "breaking changes" for those who use the `locutus` package with "^", it was way better to release it as 2.1.* or 3.*, if you want to use yarn v4...

**Comment by kvz** [comment]
Hi, while Locutus isn't SemVer, that breakage is unintentional. I though this Yarn requirement was for Locutus devs, not for consuming devs.

Relaxed the requirement in `v2.0.30` again, apologies for the break and thanks for reporting
